System_Manage/Models/Custumer.cs
using System;
using System.Collections.Generic;

namespace System_Manage.Models;

public partial class Custumer
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Address { get; set; }

    public string? Phone { get; set; }

    public string? Mst { get; set; }
}

System_Manage/Areas/Admin/Controllers/CustumersController.cs
using System.Drawing.Drawing2D;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System_Manage.Models;

namespace System_Manage.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CustumersController : Controller
    {
        private readonly SystemManageContext _db;
        private readonly INotyfService _notyf;

        public CustumersController(SystemManageContext db, INotyfService notyf)
        {
            _db = db;
            _notyf = notyf;
        }
        [Route("/Admin/Customer")]
        public async Task<IActionResult> Index()
        {
            var Custumer = await _db.Custumers
                .OrderByDescending(x => x.Id)
                .ToListAsync();

            return View(Custumer);
        }

        [Route("/Admin/Customer/Create")]
        public IActionResult Create()
        {
          
            return View();
        }

        [HttpPost]
        [Route("/Admin/Customer/Create")]
        public IActionResult Create(Custumer model)
        {

            if (ModelState.IsValid)
            {
                

                Custumer custumer = new Custumer
                {
                    Name = model.Name,
                    Address = model.Address,
                    Phone = model.Phone,
                    Mst = model.Mst,
                    
                };

                _db.Custumers.Add(custumer);
                _db.SaveChanges();
                _notyf.Success("Create Success");
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [Route("/Admin/Customer/Edit/{id:}")]
        public IActionResult Edit(int id)
        {
            Custumer custumer = _db.Custumers.Find(id);

            if (custumer == null)
            {
                _notyf.Error("Find Not Success");
                return RedirectToAction("Index");
            }


          
            return View(custumer);
        }

        [HttpPost]
        [Route("/Admin/Customer/Edit/{id:}")]
        public IActionResult Edit(int id, Custumer model)
        {
           
            if (ModelState.IsValid)
            {
                try
                {
                    var cus = _db.Custumers.Find(id);

                   


                    if (cus != null)
                    {
                        cus.Name = model.Name;
                        cus.Address = model.Address;
                        cus.Phone = model.Phone;
                        cus.Mst = model.Mst;
                       


                        _db.Custumers.Update(cus);
                        _db.SaveChanges();
                        _notyf.Success("Update Success");

                       
                        return RedirectToAction("Index");
                    }

                }
                catch
                {
                   
                    _notyf.Success("Update Faill");
                    return View(model);

                }



            }
            return View(model);
        }

        [Route("/Admin/Custumer/Delete/{id:}")]
        public ActionResult Delete(int id)
        {
            Custumer cus = _db.Custumers.Find(id);
            if (cus == null)
            {
                return RedirectToAction("Index");
                _notyf.Success("Update Faill");
            }
            else
            {
               

                _db.Custumers.Remove(cus);
                _db.SaveChanges();
                _notyf.Success("Delete Success");
                return RedirectToAction("Index");
            }
        }
    }
}

System_Manage/Areas/Admin/Views/Custumers/Create.cshtml
@model System_Manage.Models.Custumer
@{

    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}



<div class="header-sub-title">
    <nav class="breadcrumb breadcrumb-dash">
        <a class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
        <a class="breadcrumb-item" asp-area="Admin" asp-controller="Custumer" asp-action="Index">Custumer</a>
        <span class="breadcrumb-item active">Add Custumer</span>
    </nav>
</div>


<div class="card">
    <div class="card-body">
        <form id="form-validation" asp-area="Admin" asp-controller="Custumers" asp-action="Create" method="post" enctype="multipart/form-data">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label control-label">Custumer Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Name" placeholder="Custumer Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label control-label">Custumer Address</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Address" placeholder="Custumer Address">
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label control-label">Custumer Phone</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Phone" placeholder="Custumer Phone">
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label control-label">Custumer MST</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Mst" placeholder="Custumer MST">
                    <span asp-validation-for="Mst" class="text-danger"></span>
                </div>
            </div>

            <button type="submit" class="btn btn-primary m-r-5">Submit</button>
            <a class="btn btn-secondary m-r-5" asp-controller="Custumers" asp-action="Index">Back to List</a>
        </form>
    </div>
</div>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />


    <partial name="_ValidationScriptsPartial" />
}

System_Manage/Areas/Admin/Views/Custumers/Edit.cshtml
@model System_Manage.Models.Custumer
@{

    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}



<div class="header-sub-title">
    <nav class="breadcrumb breadcrumb-dash">
        <a class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
        <a class="breadcrumb-item" asp-area="Admin" asp-controller="Custumer" asp-action="Index">Custumer</a>
        <span class="breadcrumb-item active">Edit Custumer</span>
    </nav>
</div>


<div class="card">
    <div class="card-body">
        <form id="form-validation" asp-area="Admin" asp-controller="Custumers" asp-action="Edit" method="post" enctype="multipart/form-data">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label control-label">Custumer Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Name" placeholder="Custumer Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label control-label">Custumer Address</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Address" placeholder="Custumer Address">
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label control-label">Custumer Phone</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Phone" placeholder="Custumer Phone">
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label control-label">Custumer MST</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Mst" placeholder="Custumer MST">
                    <span asp-validation-for="Mst" class="text-danger"></span>
                </div>
            </div>

            <button type="submit" class="btn btn-primary m-r-5">Submit</button>
            <a class="btn btn-secondary m-r-5" asp-controller="Custumers" asp-action="Index">Back to List</a>
        </form>
    </div>
</div>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />


    <partial name="_ValidationScriptsPartial" />
}

System_Manage/Areas/Admin/Views/Custumers/Index.cshtml
@model IEnumerable<System_Manage.Models.Custumer>

@{

    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- page css -->
<link href="~/admin/assets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">

<div class="header-sub-title">
    <nav class="breadcrumb breadcrumb-dash">
        <a class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
        <span class="breadcrumb-item active">Custumer</span>
    </nav>
</div>

<a class="btn btn-outline-info btn-sm add" asp-area="Admin" asp-controller="Custumers" asp-action="Create" title="Create" style="margin-bottom: 20px">
    New Custumer <i class="bx bx-list-plus"></i>
</a>
<div class="card">
    <div class="card-body">
        <table id="data-table" class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>MST</th>
                   
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cus in Model)
                {
                    <tr>
                        <td>@cus.Name</td>
                        <td>@cus.Address</td>

                        <td>@cus.Phone</td>
                        <td>
                            @cus.Mst
                        </td>
                        
                        
                        <td>
                            <a class="btn btn-outline-success btn-sm edit" asp-area="Admin" asp-controller="Custumers" asp-action="Edit" asp-route-id="@cus.Id" title="Edit">
                                Edit <i class="fas fa-pencil-alt"></i>
                            </a>
                            <a class="btn btn-outline-danger btn-sm delete" asp-area="Admin" asp-controller="Custumers" asp-action="Delete" asp-route-id="@cus.Id" title="Delete">
                                Delete <i class="fas fa-pencil-alt"></i>
                            </a>
                        </td>

                    </tr>

                }

            </tbody>
            <tfoot>

                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>MST</th>

                    <th></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

@section Scripts {

    <!-- page js -->
    <script src="~/admin/assets/vendors/datatables/jquery.dataTables.min.js"></script>
    <script src="~/admin/assets/vendors/datatables/dataTables.bootstrap.min.js"></script>
}